spring.application.name=TheUltimateUser
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.try-it-out-enabled=true
springdoc.openapi.info.title= Mag Mutual User Search API
springdoc.openapi.info.description=API Developer demo